### ISSUE TITLE
Warning when used with react 15 because of peer dependencies on 0.14

### ISSUE THREAD

**Issue by ghost** [qimingweng/react-center-component#4]
I get this warnings everytime I run an npm install. can you please fix this to update react version in the peer dependencies.

npm WARN react-center-component@2.0.1 requires a peer of react@^0.14.0 but none was installed.
npm WARN react-center-component@2.0.1 requires a peer of react-dom@^0.14.0 but none was installed.

**Comment by qimingweng** [comment]
This was fixed in #3
